name:                pava
version:             0.1.0.0
github:              "grastello/pava"
license:             GPL-3
author:              "Gabriele Rastello"
maintainer:          "gabriele.rastello@edu.unito.it"
copyright:           "2020 Gabriele Rastello"

extra-source-files:
- README.md

synopsis:            A checker for propositional logic derivations
category:            Data

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/grastello/pava#readme>

dependencies:
- base >= 4.7 && < 5
- parsec >= 3.1.14 && < 4
- mtl >= 2.2.2 && < 3
- containers >= 0.6.2.1 && < 1
- microlens >= 0.4.11.2

library:
  source-dirs: src

executables:
  pava:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pava

